### ISSUE TITLE
Minor release 2.5.2

### ISSUE THREAD

**Issue by cchantep** [playframework/anorm#104]

**Comment by gmethvin** [comment]
@cchantep Is there anything that needs to be backported from master to 2.5.x for this? Just making sure.

**Comment by schmitch** [comment]
@gmethvin actually I backported my fix against master: https://github.com/playframework/anorm/pull/105 it should eventually be included.

**Comment by cchantep** [comment]
@schmidt I meant 2.5.2 because that's not a major release (with major changes and deprecation validation).

@gmethvin As it stay in the 2.5 major release, I would validate and merge to 2.5.x all the commits on master since the 2.5.1 was released. I could prepare a merge request for that.

**Comment by cchantep** [comment]
@gmethvin as it seems the 2.5.2 release is not yet done, I would suggest to merge #106 before doing it.

**Comment by cchantep** [comment]
Anything new there?

**Comment by schmitch** [comment]
@gmethvin could you make a release if you have some time?

**Comment by gmethvin** [comment]
done

**Comment by cchantep** [comment]
Thanks
