### ISSUE TITLE
Lower-case aliases pick same column in joins with multiple references to same table

### ISSUE THREAD

**Issue by vdichev** [playframework/anorm#122]
Anorm Version (2.5.x)

### Expected Behavior

In a query where the same table is joined with itself, aliases don't work properly.

1. Execute e.g. query `select t1.name as name1, t2.name as name2 from test t1 join test t2 on t1.id != t2.id`
2. Refer to a Row returned by query.
3. Observe that `row.apply[String]("name1")` is always equal to `row.apply[String]("name2")`.

### Actual Behavior

1. Same as above
2. Same as above
3. Observe that `row.apply[String]("name1")` is different from `row.apply[String]("name2")`.

Note that it works as expected when aliases in query are upper-case:

```sql
select t1.name as NAME1, t2.name as NAME2 from test t1 join test t2 on t1.id != t2.id
```

### Analysis and proposed solution

The problem can be traced to the `get` method in Row.scala:

```scala
    data <- MayErr(m.column.alias.flatMap(aliasesDictionary.get(_)).
      orElse(columnsDictionary.get(m.column.qualified.toUpperCase())).
```

So the qualified name is upper-cased before being retrieved from the `columnsDictionary`, but the alias is not upper-cased when retrieved from the `aliasesDictionary`. This would also explain how it works when we have the table referenced only once- it falls back to the qualified name. However when there are multiple references to a column in a table, it always picks the first one it encounters, bypassing aliases. I think the alias then should either be upper-cased upon constructing the `MetaDataItem` or, to be more consistent with how `qualified` is used in the code fragment, to be changed to this:

```scala
    data <- MayErr(m.column.alias.flatMap(a => aliasesDictionary.get(a.toUpperCase())).
```

**Comment by vdichev** [comment]
Let me know if you need a PR

**Comment by cchantep** [comment]
Hi, PR is welcome. Please make sure to add appropriate tests so it can be validated. Best regards.

**Comment by vdichev** [comment]
https://github.com/playframework/anorm/pull/125

**Comment by PanzerKunst** [comment]
Thank you for raising this issue, and creating a pull request. I am experiencing a related issue: a bug when selecting twice the same column of a given table (for example when joining twice on that table).

Sample code to illustrate:

    val query = """select d.id as order_id,
      u.id as customer_id, u.prenume as customer_first_name,
      r.prenume as rater_first_name
    from documents d
      inner join useri u on u.id = d.added_by
      inner join useri r on r.id = d.assign_to;"""

    val rowParser = long("order_id") ~
      long("customer_id") ~ str("customer_first_name") ~
      str("rater_first_name") map {
        case orderId ~
        customerId ~ customerFirstName ~
        raterFirstName =>

    [...]

In the above example, `customerFirstName` will contain the value of the `rater_first_name` column due to the bug. In the expected behaviour, `customerFirstName` would contain the value of the `customer_first_name` column.

The SQL query used in this example is simple, so I see this bug as being major.

**Comment by PanzerKunst** [comment]
Would you have an idea when a new version of Anorm will be released with this fix?
