### ISSUE TITLE
Handling deprecation of play.api.db.DB in Anorm 2.5

### ISSUE THREAD

**Issue by PanzerKunst** [playframework/anorm#127]
Hi,

I noticed that my usual Anorm code now triggered some deprecation warnings with Anorm 2.5. That code is based on the latest Anorm documentation, which is in fact outdated for Anorm 2.5, due to the usage of `play.api.db.DB`.

My old code, triggering the deprecation warnings:

    import play.api.db.DB
    
    object MyDatabaseService {
        def addSomeData {
            DB.withConnection { implicit c =>
                /* ... */
            }
        }
    }

My updated code, no deprecation warnings:

    import javax.inject.Singleton
    import play.api.db.Database
    
    @Singleton
    class MyDatabaseService @Inject() (db: Database) {
        def addSomeData {
            db.withConnection { implicit c =>
                /* ... */
            }
        }
    }
    
When I noticed this problem, I first planned to update the doc and create a pull request on Github. But I didn't manage to do it: the main issue being that I don't know how to update https://github.com/playframework/anorm/blob/master/docs/manual/working/scalaGuide/main/sql/code/ScalaAnorm.scala to use the new API.

So instead of creating a pull request, I opened this issue. Hope it helps still!

**Comment by cchantep** [comment]
Hi, the documentation about using a connection from Play DB has been updated by #129 . Best regards
