### ISSUE TITLE
How to insert curly braces when using Anorm?

### ISSUE THREAD

**Issue by PanzerKunst** [playframework/anorm#136]
Hi,

I posted that question on Stackoverflow a few days ago, but no answer. So trying here.

I've been using Anorm for a while, and now comes the moment when I need to insert curly braces. Curly braces are special characters in Anorm, as they are used to indicate placeholders to be replaced by dynamic values.

I've tried escaping curly braces with `\`, but haven't managed to make the SQL query work so far.

Can someone provide an example of a SQL query inserting curly braces?

**Comment by cchantep** [comment]
Hi,

You can consider using Anorm interpolation `SQL".."` which is not using placeholder.

> The issue tracker is not the best place to ask for helper. Please consider SO or Play MailingList.

**Comment by PanzerKunst** [comment]
I can see it working that way for sure. But since I use to log some of my SQL queries, I like to be able to put them in a String variable. Using the Anorm interpolation prevents me from doing that.

I was rather hoping for some system that would enable me to "escape" the curly braces, so that they would be interpreted as a standard character instead of a placeholder indicator.

So at the end of the day I'll be using JDBC for this specific query.

I prefer Anorm over JDBC, and would love if I could ditch JDBC completely. But this is the second SQL query in my project when JDBC is (sadly) better than Anorm for me. The first case being due to issue https://github.com/playframework/anorm/issues/122 which has been fixed but not released yet.

**Comment by cchantep** [comment]
- [How to configure SQL log statement](https://www.playframework.com/documentation/2.5.x/ScalaDatabase#How-to-configure-SQL-log-statement)
- See https://github.com/playframework/anorm/pull/137
