### ISSUE TITLE
The executeInsert can't return a string type primary key

### ISSUE THREAD

**Issue by wangty6** [playframework/anorm#142]
### Anorm Version (2.5.x / etc)

2.5.0

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Windows 10

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

scala 2.11
play 2.5.9

### Actual Behavior

Please provide a description of what actually happens, working from the same starting point.

Be descriptive: "it doesn't work" does not describe what the behavior actually is -- instead, say "java.time.LocalDate is not accepted as a statement parameter "  Copy and paste logs, and include any URLs.

```
val list = SQL"INSERT INTO wordnote.word (word,translate) VALUES ({word}, {translate})"
              .on("word" -> input.word, "translate" -> input.translate)
              .executeInsert(scalar[String].singleOpt)
```
The result is alwasy None, changed a few Parser like scalar[String].*, no use. I'm certain the primary key of db is charsequence

**Comment by cchantep** [comment]
Hi,

Anorm tests are covering the case that as long as the generated key is available through the JDBC driver, it can be parsed as elsewhere in the API; See [test](https://github.com/playframework/anorm/blob/master/core/src/test/scala/anorm/AnormSpec.scala#L490).

As this cannot be confirmed as an issue (as indicated in the tracker guide), it's recommanded to first discuss/ask for help; See [Anorm at SO](http://stackoverflow.com/questions/tagged/anorm).

Best regards
