### ISSUE TITLE
3.0.0-M1 published for 2.11, but not 2.12

### ISSUE THREAD

**Issue by wsargent** [playframework/anorm#149]
There is a 2.11 version:

https://mvnrepository.com/artifact/com.typesafe.play/anorm_2.11/3.0.0-M1

but no 2.12 version:

but no https://mvnrepository.com/artifact/com.typesafe.play/anorm_2.12/3.0.0-M1

**Comment by cchantep** [comment]
3.0 should never have been published, latest stable is 2.5

**Comment by wsargent** [comment]
Okay, so I should revert https://github.com/playframework/play-scala-anorm-example/blob/SNAPSHOT/build.sbt#L14 to 2.5.0 then...

**Comment by wsargent** [comment]
@cchantep also, if you can review the async boundary / execution context I put around the anorm code in https://github.com/playframework/play-scala-anorm-example/blob/SNAPSHOT/app/models/ComputerRepository.scala it is running db operations in a different thread pool now.

**Comment by cchantep** [comment]
The latest minor is 2.5.3 @wsargent
