### ISSUE TITLE
Incorrect simpleLiteral regex in SqlStatementParser fails on valid SQL containing ^ characters

### ISSUE THREAD

**Issue by mechkg** [playframework/anorm#150]
Valid SQL that is incorrectly tokenized: `ALTER TABLE surveys ADD CONSTRAINT surveys_id_characters CHECK (id ~ '^[A-Za-z0-9_-]+$')`

[simpleLiteral regex](https://github.com/playframework/anorm/blob/a0826ab507e1eac2b5435b0382b23df919b678af/core/src/main/scala/anorm/SqlStatementParser.scala#L33) is intended to match anything but `%`, `{` and `\`, but will also stop on `^` because it is included in the character class. 

Only one initial `^` is required for character class negation, so the correct regex is: `[^%{\\]+`

**Comment by cchantep** [comment]
Hi, PR is welcome.

> BTW I would rather pass value as argument, to avoid tokenization: `SQL"""ALTER TABLE surveys ADD CONSTRAINT surveys_id_characters CHECK (id ~ ${"^[A-Za-z0-9_-]+$"})"""`
