### ISSUE TITLE
Connection in Column.nonNull

### ISSUE THREAD

**Issue by schmitch** [playframework/anorm#151]
Currently it would be great if there was a way to get the current connection inside a `Column.nonNull block`. (or well maybe consider a `Column.nonNullWithConnection` block

At the moment there are various Conversion which can be made directly by the drive if somebody want's his own Column types, considering supporting a Range Type with LocalDateTime, where PGConnection will actually have a converter for the String value to LocalDateTime: https://github.com/pgjdbc/pgjdbc/blob/master/pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java#L425

**Comment by cchantep** [comment]
I don't think it fit the design. There should be a stable/pure instance of the typeclass `Column` for one type `T`, but you can define this instance according the context as you want, including according the connection/connection pool.

**Comment by schmitch** [comment]
currently I'm not understanding what you exactly mean. What I want is to have access to `java.sql.Connection`. Then I can unwrap it and use function of the connection inside  a `Column.nonNullWithConnection` or so block.

**Comment by cchantep** [comment]
```
val foo = { implicit con: Connection =>
  implicit def myStrCol = Column.nonNull[T] {
    // can access Connection
  }
}
```

For me that's an edgecase that should not impact the "pure" design of `Column`.

**Comment by schmitch** [comment]
it's highly unlikely that I define a row parser inside a connection block.

**Comment by cchantep** [comment]
"it's highly unlikely that I define a row parser inside a connection block" but indeed it correspond to you dependencies ...

For now, I'm not for such `Connection => Column[T]`
