### ISSUE TITLE
Publish anorm-postgres to Maven Central.

### ISSUE THREAD

**Issue by lavrov** [playframework/anorm#159]

**Comment by cchantep** [comment]
The issue is more "Publish the latest version" (all modules)

**Comment by mkosovec** [comment]
Second this - currently debating building my own internal repository just to host the most recent version instead of having everyone publish locally.
The Postrges module is by far the most simple/clean way to bridge the gap between jsonb and jsValues in play.

**Comment by btmcnellis** [comment]
Is there any update on when this might be published @cchantep?

**Comment by cchantep** [comment]
I cannot answer

**Comment by richdougherty** [comment]
I think @marcospereira was going to do this. Last I heard he was [asking on Gitter](https://gitter.im/playframework/contributors?at=5a32e978232e79134d4e553a) about the version number.

**Comment by cchantep** [comment]
Thx for the feedback. There have several "ill-published" artifacts for Anorm (as 2.6.0-M1 or 3.0.0-M1). As there is no major API change/breakage on the existing modules (already published as 2.5.3), I don't see reason the master modules would not be published as 2.5.4. Best regards.

> See #162

**Comment by gmethvin** [comment]
There are a number of compatibility issues, so I think we should bump the major version. There were a lot of binary issue filters added in #147 and that has not yet been released. I'm assuming we're following the Play epoch.major.minor where we avoid breaking changes in "minor" versions but can break things in "major" versions.

Another thing we could do is drop scala 2.11 support for 2.6.0, which will make it easier to add methods to traits (as you did in #147) without breaking bincompat. It would also be nice to add scala 2.13 support soon.

Given that the versioning scheme is different from that of Play, I wonder if we should consider going straight to 3.0.0. anorm-postgres is a new "feature" so it seems like enough justification. Some users have been a bit confused by the fact that play-json still uses similar versions to Play but is not released concurrently. This might be an opportunity to help avoid that kind of confusion for anorm.

**Comment by gmethvin** [comment]
Not sure if you noticed but there are several public methods that are incompatible: https://github.com/playframework/anorm/pull/147/files#diff-fdc3abdfd754eeb24090dbd90aeec2ceR81. You added methods to `Column`: https://github.com/playframework/anorm/pull/147/files#diff-b16d230677d928f6fa2f6cb6eb1abab5R68.

**Comment by cchantep** [comment]
Adding function is not the kind of evolution which deserve a major bump for me, as it doesn't raise backward compatibility issue for the existing user.

**Comment by richdougherty** [comment]
Hi @cchantep, we've talked about version numbers quite a bit, so maybe a solution is if you can make releases yourself? How about we create a new groupId on Sonatype/Maven Central. We can create a groupId `org.playframework` for community maintained projects. Perhaps anorm artifacts can be published under `org.playframework.anorm`. If that's OK with you I'll go ahead and create the new project.

If you email or message me your Sonatype account name then I'll give you access. If you don't yet have an account see "Create your JIRA account" on this page for instructions: http://central.sonatype.org/pages/ossrh-guide.html.

**Comment by cchantep** [comment]
Hi, a groupId `org.playframework.anorm` could be fine. My username at Sonatype is the same as there. Thx.

**Comment by richdougherty** [comment]
Issue created: https://issues.sonatype.org/browse/OSSRH-36649. This will create `org.playframework` so you should have access to `org.playframework.anorm` too.

**Comment by cchantep** [comment]
Thx @richdougherty , will check it.

**Comment by richdougherty** [comment]
@cchantep I think it's all set up now. There's a [comment on the ticket giving the status](https://issues.sonatype.org/browse/OSSRH-36649?focusedCommentId=453474&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-453474). It also says "please comment on this ticket when you promoted your first release" so can you leave a comment once you've published something?

**Comment by cchantep** [comment]
@richdougherty Nothing published for now, but prepared on #162 . Seems ok for now: https://oss.sonatype.org/content/repositories/orgplayframework-1000/
