### ISSUE TITLE
Allow to set the transaction isolation level

### ISSUE THREAD

**Issue by AlexITC** [playframework/anorm#175]
At the moment, there is no way to specify the transaction isolation level for a single transaction, it would be great to have a syntax like this:
 ```scala
database.withTransaction(TransactionIsolationLevel.Serializable) { implicit conn => ... }
```

The code changes to support that are trivial, would you accept a pull request?

**Comment by cchantep** [comment]
Hi @AlexITC , Anorm core is not intended to manage the connection, but to be provided one.

BTW, I guess the `database` is the one from Play JDBC, is such case the discussion should be moved in appropriate place.

Best regards.

**Comment by AlexITC** [comment]
You are right, thanks!
