### ISSUE TITLE
Release for Scala 2.13.0-M3

### ISSUE THREAD

**Issue by marcospereira** [playframework/anorm#179]
Notice that Anorm does not have a 2.13.0-M3 build when trying to add support for Omnidoc:

https://github.com/playframework/omnidoc/issues/20

We may want to remove the duplication of publishing Anorm docs there (since they are already published [here](https://playframework.github.io/anorm/)), but applications using Play, Anorm may still need Scala 2.13 support.

**Comment by cchantep** [comment]
Missing dependencies:

```
[error] (anorm/*:update) sbt.ResolveException: unresolved dependency: com.jsuereth#scala-arm_2.13.0-M4;2.0: not found
[error] unresolved dependency: org.scala-lang.modules#scala-parser-combinators_2.13.0-M4;1.0.4: not found
[error] unresolved dependency: org.eu.acolyte#jdbc-scala_2.13.0-M4;1.0.49: not found
[error] unresolved dependency: com.chuusai#shapeless_2.13.0-M4;2.3.2: not found
```

**Comment by marcospereira** [comment]
Hi @cchantep,

- `scala-parser-combinators` need to use [version `1.1.0`](http://mvnrepository.com/artifact/org.scala-lang.modules/scala-parser-combinators_2.13.0-M3/1.1.0)
- `shapeless` need to use [version `2.3.3`](http://mvnrepository.com/artifact/com.chuusai/shapeless_2.13.0-M3/2.3.3)

Acolyte is the only missing a build for Scala 2.13.0-M3.

Best.
