### ISSUE TITLE
Mysql JSON_UNQUOTE support

### ISSUE THREAD

**Issue by yueshuai** [playframework/anorm#216]
[JSON_UNQUOTE](https://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html#operator_json-inline-path) command is a useful Mysql command to extract values from JSON without double quotes because JSON_EXTRACT returns the double quotes. It appears that Anorm does not support this command. We got the following error
```
anorm.AnormException: TypeDoesNotMatch(Cannot convert [B@2845af: [B to String for column ColumnName(.JSON_UNQUOTE(payload->'$.data[0]')),Some(JSON_UNQUOTE(payload->'$.data[0]')))))
```
for a selection query like 
```sql
SELECT JSON_UNQUOTE(payload->'$.data[0]')
```
It would be appreciated if you could consider adding support for it. Thank you!

**Comment by yueshuai** [comment]
Similarly, `REPLACE` command for string replacement is not supported either (trying to work around the JSON_UNQUOTE command by replacing double quotes). Essentially when we define a selection query statement in `SQL()` with some extra command around the column name, Anorm seems to complain about it. Is there a way to run the query as is without being too start and try to parse it?

**Comment by cchantep** [comment]
Anorm is totally agnostic of databases commands/functions, it's up to you to use appropriate column parser.

> BTW this issue tracker is for confirmed issue/actionable request. To ask for help/question, rather use [SO](https://stackoverflow.com/questions/tagged/anorm).
