### ISSUE TITLE
exception during macro expansion error with openjdk11, sbt 1.3.3 and scala 2.12.10

### ISSUE THREAD

**Issue by Bunyod** [playframework/anorm#256]
I'm receiving a lot of errors [error] /root/something-updates/src/main/scala/Something.scala:67:92: exception during macro expansion: 

------------------
[error] java.lang.AssertionError: assertion failed: List(package anorm, package anorm)
... // I skipped long long messages
[error] 	at anorm.macros.ToParameterListImpl$.caseClass(ToParameterListImpl.scala:80)
[error] 	at anorm.Macro$.configuredParameters(Macro.scala:430)
-------------------

[error] /root/something-updates/src/main/scala/com/something/infrastructure/SomeUpdatesRepository.scala:74:89: exception during macro expansion: 
[error] java.lang.AssertionError: assertion failed: import failure: cannot determine unique overloaded method alternative from
[error]  final package anorm
[error] final package anorm
[error]  that matches package anorm:anorm.type
....
[error]   implicit private def ToParams: ToParameterList[MyCaseClass] = Macro.toParameters(

------------------

[error] /root//src/main/scala/something/updates/MyRepository.scala:66:92: exception during macro expansion:
[error] java.lang.AssertionError: assertion failed:
[error]   anorm package anorm <none>
[error]      while compiling: <no file>
[error]         during phase: globalPhase=<no phase>, enteringPhase=typer
[error]      library version: version 2.12.10
[error]     compiler version: version 2.12.10
[error]   reconstructed args:
[error]   last tree to typer: EmptyTree
[error]        tree position: <unknown>
[error]             tree tpe: <notype>
[error]               symbol: null
[error]            call site: package <root> in <none>
[error] == Source file context for tree position ==
[error] 	at scala.reflect.internal.SymbolTable.throwAssertionError(SymbolTable.scala:184)
-----------------------
**This is the definition of my case class:** 

implicit private def toParamsFlightInfo: ToParameterList[FlightInfo] = Macro.toParameters(
    Macro.ParameterProjection(propertyName = "startDatetime", parameterName = "start_datetime"),
    Macro.ParameterProjection(propertyName = "arrivalDatetime", parameterName = "arrival_datetime"),
    Macro.ParameterProjection(propertyName = "classCode", parameterName = "class_code"),
    Macro.ParameterProjection(propertyName = "airportCode", parameterName = "airport_code")
  )

---------
Are these errors related to java version and sbt version?

**Comment by Bunyod** [comment]
Used versions:

scala: 2.12.10
sbt: 1.3.3
openjdk: 11.0.5
openjdk: 1.8u212
anorm: 2.6.5

**Comment by cchantep** [comment]
Not reproduced (sbt 1.3.5, scala 2.12.10, openjdk 11.0.3, anorm 2.6.5):

```scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

import anorm._

case class FlightInfo(
  startDatetime: Long,
  arrivalDatetime: Long)

implicit private def toParamsFlightInfo: ToParameterList[FlightInfo] =
  Macro.toParameters(
    Macro.ParameterProjection(propertyName = "startDatetime", parameterName = "start_datetime"),
    Macro.ParameterProjection(propertyName = "arrivalDatetime", parameterName = "arrival_datetime"),
    Macro.ParameterProjection(propertyName = "classCode", parameterName = "class_code"),
    Macro.ParameterProjection(propertyName = "airportCode", parameterName = "airport_code")
)

// Exiting paste mode, now interpreting.

import anorm._
defined class FlightInfo
```

**Comment by Bunyod** [comment]
I see, you are right it's not happening in compilation, but when I call `debian:packageBin, I'm seeing this error.

Any clue?

**Comment by cchantep** [comment]
> I see, you are right it's not happening in compilation, but when I call `debian:packageBin, I'm seeing this error.
> 
> Any clue?

Check with the support of this SBT plugin.
