### ISSUE TITLE
Regression error between Anorm 2.6.2 and 2.6.5

### ISSUE THREAD

**Issue by bwbecker** [playframework/anorm#276]
### JDK
% java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)

### Library Dependencies

% postgres --version
postgres (PostgreSQL) 12.1

running locally on MacOS 10.15.3

### Expected Behavior

The following code behaves differently under Anorm version 2.6.2 and version 2.6.4/2.6.5.  It's running as part of a Play app.

```
       try {
          dbapi.database("default").withConnection { implicit c ⇒
            import anorm.SqlParser.{str, int}
            val parser = int("billy") ~ str("bob") map { case a ~ b ⇒ (a → b) }
            val b      =
              SQL"""
                  SELECT 1 as billy, null as bob
                  """.as(parser.single)
          }
        } catch {
          case e: Exception ⇒
            println(s"\n${e}\n")
        }
  ```

When my scala project uses the dependency `"org.playframework.anorm" %% "anorm" % "2.6.2"` it prints 

```anorm.AnormException: UnexpectedNullableFound(ColumnName(.bob,Some(bob)))```

I would expect it to do the same with the dependency `"org.playframework.anorm" %% "anorm" % "2.6.5"` 

### Actual Behavior

When depending on     `"org.playframework.anorm" %% "anorm" % "2.6.5"` the code above prints 

```
anorm.AnormException: 'bob' not found, available columns: billy, billy, bob, bob
```

### Reproducible Test Case

Sorry, I tried, but I just couldn't figure out the testing framework in a reasonable amount of time.

**Comment by cchantep** [comment]
Hi, I don't see the point. Are you depending on the exception message in anyway?

**Comment by bwbecker** [comment]
Yes, I was.  I took another look at parser options and figured out how to distinguish the four cases I'm concerned about without the exceptions. Sorry for the trouble.

**Comment by cchantep** [comment]
Except when explicitly specified, message of exception are purely informal, not part of the API, not covered by API compatibility/version.

It's highly discouraged to depend on it.
