### ISSUE TITLE
java.time.LocalDateTime cannot be converted to Java8 LocalDateTime

### ISSUE THREAD

**Issue by dinoboy197** [playframework/anorm#329]
Anorm has become unable to parse a `LocalDateTime` from a MySQL database. This has worked wonderfully for me until just recently - a few days back. I suspect some other library that has recently been updated may be at play (no pun intended), but I haven't been able to pinpoint the source of the change. However, the error seems to point to something that I suspect Anorm _should_ handle - accepting a `java.time.LocalDateTime` as a `LocalDateTime` - `TypeDoesNotMatch(Cannot convert 2011-03-13T02:49:10: java.time.LocalDateTime to Java8 ZonedDateTime for column ColumnName`.

I'm very happy to provide more detail around my specific failure case if it helps to narrow down how to replicate, or what the issue might be. For now, I've put in a minimal amount of detail in case the problem or fix seems obvious to someone else.

### Anorm Version (2.5.x / etc)

2.6.8

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Ubuntu 18.04 (Kernel version 4.15.0-132-generic)

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

OpenJDK 15.0.1 (build 15.0.1+9-18)

### Library Dependencies

* `mysql-connector-java` version 8.0.23
* `play-json` version 1.7.2
* `play-framework` version 2.8.2
* Scala 2.13.4

### Expected Behavior

1. Create MySQL table: 

```
CREATE TABLE examples (
  id varchar(64) NOT NULL,
  local_datetime datetime NOT NULL,
  time_zone varchar(64) NOT NULL,
  data varchar(256) DEFAULT NULL,
  PRIMARY KEY (`id`)
);
```

2. Insert row into table
```
INSERT INTO `examples` VALUES ('5b7c9d70-5e51-4ea0-bd0a-75457d7737ca','2011-03-13 02:49:10','Africa/Dar_es_Salaam','other data');
```

3. Create parser:
```
val EXAMPLE_PARSER: RowParser[Example]  = {
  get[UUID]("id") ~
  get[LocalDateTime]("local_datetime") ~
  get[String]("time_zone") ~
  get[Option[String]]("data") map { case id ~ localDateTime ~ timeZone ~ data =>
    Example(id, localDateTime.atZone(ZoneId.of(timeZone)), data)
  }
}
```

4. Query for data, and format using parser:
```
SQL"""SELECT * FROM examples""".as(ExampleDAO.EXAMPLE_PARSER.*)
```

### Actual Behavior

On step 4 above, Anorm reports an error in deserializing the `Example` record. It reports the exception `anorm.AnormException: TypeDoesNotMatch(Cannot convert 2011-03-13T02:49:10: java.time.LocalDateTime to Java8 ZonedDateTime for column ColumnName(examples.local_datetime,Some(local_datetime)))`

### Reproducible Test Case

I'm not quite sure what additional test needs to be added to `JavaTimeSpec` to show this failure.

**Comment by pschichtel** [comment]
I think this one is caused by the latest MySQL driver directly returning LocalDateTime instances, which Anorm does not check:

https://github.com/playframework/anorm/blob/master/core/src/main/scala/anorm/Column.scala#L727-L733

**Comment by pmcq** [comment]
@pschichtel sorry to comment on an old issue but this seems like it is still a problem for reading into a Java8 Instant:

```
anorm.AnormException: TypeDoesNotMatch(Cannot convert 2021-08-10T13:52:34: java.time.LocalDateTime to Java8 Instant for column ColumnName(some_table.first_seen,Some(first_seen)))
```

Seems like a similar code change may be needed here?
https://github.com/playframework/anorm/blob/master/core/src/main/scala/anorm/Column.scala#L713-L722

**Comment by pschichtel** [comment]
Yep, seems like it.

**Comment by cchantep** [comment]
Try 2.6.11-4f5b85fa-SNAPSHOT.
Also if you have question, rather use [SO tag](https://stackoverflow.com/questions/tagged/anorm).
