### ISSUE TITLE
Parsing ResultSet directly

### ISSUE THREAD

**Issue by giangstrider** [playframework/anorm#370]
Hi,

I have an edge case where I can't use Anorm's utility to execute a query, I need to use raw JDBC instead.
I'm wondering if is there any ways which I can still using Anorm Parsing (to case class) utility by passing ResultSet directly into it.

Regards

**Comment by cchantep** [comment]
No, and that's not plan. But everywhere you can use raw JDBC, you can use Anorm.
Anyway this tracker is for confirmed issue, so please rather ask question on [SO](https://stackoverflow.com/questions/tagged/anorm).
