### ISSUE TITLE
Document changes in member visibility since 2.3

### ISSUE THREAD

**Issue by jawshooah** [playframework/anorm#42]
In a4c9031, the visibility of `Row.metaData` was changed from `public` to `private[anorm]`. However, the 2.4 Migration Guide makes no mention of this change, which was breaking in my case.

Since it was exposed as a public member in previous versions of the API, I imagine I'm not the only one who encountered this issue when upgrading to Play 2.4. It would be helpful to add a note, however brief, that explains the change and how best to refactor around it.

**Comment by cchantep** [comment]
(This change was introduced in Play 2.3.6) What is the case using this value?

**Comment by jawshooah** [comment]
[Are you sure?](https://github.com/playframework/playframework/blob/2.3.6/framework/src/anorm/src/main/scala/anorm/Row.scala) I've been running Play 2.3.7 and haven't had a problem.

The code looks something like this:

```scala
val cells = for (m <- row.metaData.ms) yield {
  val qualifiedName = m.column.qualified
  val rawValue = m.clazz match {
    case "java.lang.Integer" => row[Int](qualifiedName)
    case "java.lang.Long"    => row[Long](qualifiedName)
    ...
  }
  ResultCell(rawValue)
}
```

**Comment by cchantep** [comment]
(See the deprecation annotation in the commit)

It looks like the code is doing `Column` extraction not using `Column`. I guess it should be better to make it as custom instance of `Column` (end of section in doc: https://github.com/playframework/anorm/blob/master/docs/manual/working/scalaGuide/main/sql/ScalaAnorm.md#column-parsers ).

```scala
// having defined `customColum`
val rowParser = get("columnName")(customColumn) ~ ...
```

**Comment by jawshooah** [comment]
Which deprecation annotation? I'm not seeing one for `metaData`.

The problem is that we don't know the names or data types of the columns before retrieving the result set. The application retrieves and transforms arbitrary data from a schema we intentionally know nothing about at run time. I'm not sure how we could create a custom row parser with the `Column` API in this case.

**Comment by cchantep** [comment]
(Deprecation annotation elsewhere in the same commit indicates that's 2.3.6)

You try to parse row without any column contraint ? Column positions or names ? (That's a quite uncommon use case of Anorm for me)

**Comment by cchantep** [comment]
Additional: do you know the number of column to be considered?

**Comment by jawshooah** [comment]
(I'm still not sure what you mean. I've looked through the commit tagged as 2.3.6, and cannot find a deprecation annotation for `Row`'s public `metaData` member. Further, if such an annotation existed, wouldn't I see a deprecation warning when compiling with `-deprecation`?)

Right, we don't know at runtime what kind of data each column will contain, or even how many columns there are. We encapsulate the result set in a generalized `ResultDataset` class, which itself contains a `Seq[ResultRow]`, each of which contains a `Seq[ResultCell]`.

**Comment by cchantep** [comment]
The `metaData` wasn't meant to be public and btw was not documented, that's why it has been made private (without deprecation). 

Since it won't be made public again, another solution should be designed for such edge cases.

Best regards

**Comment by jawshooah** [comment]
I see, `metaData` was never intended to be public in the first place. I believe we discovered it through the [ScalaDoc](https://playframework.com/documentation/2.3.x/api/scala/index.html#anorm.Row) and proceeded from there.

Should I open a separate issue requesting API support for my use case?

**Comment by cchantep** [comment]
Nope, a PR can be directly attached to this issue.

**Comment by jawshooah** [comment]
What do you suggest, given my example above? Shall I open a PR that exposes a public member `metaDataItems: Seq[MetaDataItem]`, assuming you'd prefer to keep the `MetaData` class private?
