### ISSUE TITLE
Boolean columns broken with MariaDB driver v3

### ISSUE THREAD

**Issue by bursauxa** [playframework/anorm#432]
After upgrading the MariaDB JDBC driver from version 2 to version 3, boolean columns (SQL type `BOOLEAN`, Scala type `Boolean`) fail to be parsed.

I have not dug deeply into the root cause, but it could be that metadata reports them as `Byte` instead. I guess that makes sense to some degree, as MariaDB booleans are really synonyms for `tinyint(1)` according to [the docs](https://mariadb.com/kb/en/boolean/). The French docs even mention that SQL-compliant boolean implementations will come in a future version, but for some reason this mention is absent in the English docs.

In any case, it seems acceptable to handle the *byte -> boolean* case as a match in `columnToBoolean`. I realize that there is documentation explaining how to do it with [custom mappings](https://www.playframework.com/documentation/2.6.x/ScalaAnorm#JDBC-mappings), but it seems so "standard" that I believe it should be part of the default mapping. Case in point, the symmetric *boolean -> byte* case is already implemented in `columnToByte`.

### Anorm Version

2.6.10

### JDK

Java 11

### Library Dependencies

"org.mariadb.jdbc" % "mariadb-java-client" % "3.0.3"

### Expected Behavior

`RowParser[Boolean]` works on column that are declared in SQL script as type `BOOLEAN`

### Actual Behavior

`RowParser[Boolean]` throws the following:

> anorm.AnormException: TypeDoesNotMatch(Cannot convert 1: java.lang.Byte to Boolean for column ColumnName(my_table.myBoolean,Some(myBoolean)))

**Comment by cchantep** [comment]
"it seems acceptable to handle the byte -> boolean" only to some degree ... I'm not found to make that the common behaviour.

On the other hand, that's easy to have a maria db specific handler.

**Comment by bursauxa** [comment]
@cchantep While I agree that there can be a philosophical argument about how this should be handled by the driver and not Anorm, I find it hard to justify not having it as common behavior when we have this line in `columnToByte`:

```scala
      case bool: Boolean => Right(if (!bool) 0.toByte else 1.toByte)
```

This boolean/integer mixup scenario is so common that the documentation on custom mappings (link added to original post) uses it as the go-to example.
