### ISSUE TITLE
CI Release doesn't work

### ISSUE THREAD

**Issue by cchantep** [playframework/anorm#485]
https://github.com/playframework/anorm/runs/8057319820?check_suite_focus=true

**Comment by ihostage** [comment]
Hmmm 🤔 
It should have use a `sonatypeProfileName := "com.typesafe.play"` from interplay.
https://github.com/playframework/interplay/blob/f4c53f02edda8afd0000e4ccee7db7b0a3c8bd1e/src/main/scala/interplay/PlaySonatypeBase.scala#L15

@cchantep Cedric, can you try to set `sonatypeProfileName` explicitly? As I see in log, it used a [default SBT organization](https://github.com/xerial/sbt-sonatype#project-rootsonatypesbt) value `org.playframework.anorm` for publishing and it's incorrect.

**Comment by cchantep** [comment]
I don't know the credentials.

**Comment by ihostage** [comment]
It isn't matter, because cred's stored in organization secrets, mapped to environment variables and worked fine for other repo's. I think that problem only with one `sonatypeProfileName` setting for `sbt-sonatype` plugin.

**Comment by mkurz** [comment]
Actually it looks like the release went through:

- https://repo1.maven.org/maven2/org/playframework/anorm/anorm_3/2.7.0/
- https://repo1.maven.org/maven2/org/playframework/anorm/anorm_2.13/2.7.0/
- https://repo1.maven.org/maven2/org/playframework/anorm/anorm_2.12/2.7.0/

the `playframework` user does have permissions to publish to `org.playframework`, see https://issues.sonatype.org/browse/OSSRH-36649?focusedCommentId=1161510&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1161510 where I applied for access in April.

@cchantep Can you confirm all artifacts got published correctly? I just pulled in anorm 2.7.0 with Scala 2.13 into  Play application and it looked good.

**Comment by mkurz** [comment]
BTW: Actually I was thinking to move anorm to `play.typesafe` as well, see https://github.com/playframework/anorm/pull/162#issuecomment-1109675297
Not sure if it's worth it, or maybe even move all the Play artifacts to `com.typesafe` with one of the next major releases...

**Comment by mkurz** [comment]
@cchantep So did you check, are the artifacts ok?

**Comment by cchantep** [comment]
I published the artifacts manually, as the CI was not working

**Comment by mkurz** [comment]
> I published the artifacts manually, as the CI was not working

Ah ok...Hmm.. Not sure then what the problem was. All credentials should be ok and in place and the user should have permissions to publish to `org.playframework.anorm`.... maybe just a temporary problem? Let's just see what happens next time.

**Comment by mkurz** [comment]
I asked in the sonatype JIRA if we actually do have permissions to publish to sub ids: https://issues.sonatype.org/browse/OSSRH-36649?focusedCommentId=1198681&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1198681
Just to make sure.

**Comment by mkurz** [comment]
Their answer is
> The playframework user has permissions on the top-level groupId, org.playframework. This means that you can publish under that groupId or any sub-groups that look like org.playframework.* without creating any further JIRA issues.

So I think this was just a temporary problem (hopefully). Let's close this and see if next time the release works.

**Comment by mkurz** [comment]
I finally got it, we have to configure a different sonatype profile name to publish to, fixed in #489

@cchantep this should work now, pushing a tag should now deploy it to maven central next time.

**Comment by ihostage** [comment]
It seems my guess (https://github.com/playframework/anorm/issues/485#issuecomment-1232804092) was close 😄
Good work, Matthias! 👍 Plus one repo with automate releases 🕺
