### ISSUE TITLE
404 for https://playframework.github.io/anorm/CONTRIBUTING.html

### ISSUE THREAD

**Issue by mkurz** [playframework/anorm#500]
https://playframework.github.io/anorm/CONTRIBUTING.html
This page is linked at bottom of https://playframework.github.io/anorm/
I will centralise contributor guidlines in `.github` repo anyway.

**Comment by ihostage** [comment]
Did this issue resolve in https://github.com/playframework/anorm/pull/502?

**Comment by mkurz** [comment]
Ah yes, thanks!
