### ISSUE TITLE
RowParsers on multiple joins of the same table don't resolve to the expected field in the result.

### ISSUE THREAD

**Issue by srushingiv** [playframework/anorm#55]
I have a pair of MySQL tables:

Table A { "id" varchar }
Table B { "a_ref" varchar, "discriminator" number, "value" varchar }

populated with:
> A {
>   'abc'
> }
> B {
>   'abc', 0, 'a-0'
>   'abc', 1, 'a-1'
> }

I use the following scala code:
>    SQL("""
>        select A.id, c.value cval, d.value dval
>        from A, B c, B d
>        where c.a_ref = A.id and c.discriminator = 0
>        and d.a_ref = A.id and d.discriminator = 1
>    """).as( str("id") ~ str("cval") ~ str("dval") map(flatten) *)

What I am getting back is:
> List((abc,a-0,a-0))

What I am expecting is:
> List((abc,a-0,a-1))

If I wrap the query an an inner query, this problem goes away. For example:
>    SQL("""
>        select id, cval, dval from (
>        select A.id, c.value cval, d.value dval
>        from A, B c, B d
>        where c.a_ref = A.id and c.discriminator = 0
>        and d.a_ref = A.id and d.discriminator = 1) t
>    """).as( str("id") ~ str("cval") ~ str("dval") map(flatten) *)

I am currently using version 2.4.0 of anorm.

Thank you for your time. Best regards.

**Comment by cchantep** [comment]
Hi, please first move the question to [SO](http://stackoverflow.com/questions/tagged/anorm), with the result of the query from CLI. Best regards.
