### ISSUE TITLE
Add Logging Back In

### ISSUE THREAD

**Issue by gabosgab** [playframework/anorm#57]
Hello,

I'm trying to get anorm to log and it's currently putting out nothing according to this configuration.  I scanned the source and don't see any logging in there, so I'm guessing something changed?

http://stackoverflow.com/questions/30647074/how-to-enable-trace-debugging-output-with-anorm-on-play-2-4-0

**Comment by cchantep** [comment]
Hi, there is no logging planed. If using a JDBC pool, you can configure logging with that.

> The [SO tag](http://stackoverflow.com/questions/tagged/anorm) is where to ask such question, rather than this tracker (dedicated to confirmed issue).

Best regards

**Comment by cchantep** [comment]
The answer has been updated on SO.
