### ISSUE TITLE
Pekko alternative for AkkaStream

### ISSUE THREAD

**Issue by kaplanbar** [playframework/anorm#571]
Are there any alternatives for [AkkaStream](https://github.com/playframework/anorm/blob/main/akka/src/main/scala/anorm/AkkaStream.scala) to use with Pekko?

**Comment by cchantep** [comment]
Not currently

**Comment by kaplanbar** [comment]
> Not currently

I created a PR, would you be interested merging it? https://github.com/playframework/anorm/pull/572

**Comment by ihostage** [comment]
Implemented in #572
