### ISSUE TITLE
v2.8.0 was compiled against non LTS Scala 3 version

### ISSUE THREAD

**Issue by gaeljw** [playframework/anorm#624]
_Again, thanks for releasing v2.8.0._

Unfortunately, it has been compiled against Scala 3.5.2 whereas I would have expected it to be released for the latest Scala LTS, that is 3.3.x+.

I'm not sure if this makes sense to release a 2.8.1 fixing this or if this was intended. AFAIK libraries are supposed to compile against Scala 3 LTS versions to avoid forcing users to upgrade.

**Comment by mkurz** [comment]
IMHO we shoud release 2.8.1 build against Scala 3.3.x
