### ISSUE TITLE
java.time.LocalDate is not accepted as a statement parameter

### ISSUE THREAD

**Issue by ricardobarone** [playframework/anorm#65]
`java.time.LocalDate` support was introduced in 2.5, but creating a statement with this type as a parameter, like:
```
SQL( "update some_table set some_date = {date}" )
  .on( 'date -> someLocalDateVariable )
  .executeUpdate()
```

...fails with the following error:
`type mismatch; found : (Symbol, java.time.LocalDate) required: anorm.NamedParameter`

It seems that `JavaTimeToStatement` trait does not support it yet.

**Comment by Tooa** [comment]
Same problem:

`val value = SQL"""SELECT id FROM table WHERE date = $date;""".as(get[Long]("id").singleOpt)`

For joda date value it's working with this import `anorm.JodaParameterMetaData._`. There is another import for java date values `anorm.JavaTimeParameterMetaData`. However, it does not work for the java date case.

**Comment by cchantep** [comment]
Hi, please either use the [MailingList](https://groups.google.com/forum/#!forum/play-framework) or [StackOverflow tag](http://stackoverflow.com/questions/tagged/anorm) to ask question (this issue tracker is for actionable issue/improvement). Best regards.

**Comment by Tooa** [comment]
Thanks. FYI: http://stackoverflow.com/questions/32783786/anorm-2-5-doesnt-work-with-java-time-localdate

**Comment by alex-on-java** [comment]
@cchantep as I understand this issue is still an issue. Do you (other maintainers) have any plans to fix it?
