### ISSUE TITLE
Update the documentation

### ISSUE THREAD

**Issue by cchantep** [playframework/anorm#75]
Have a place where Anorm documentation can be up-to-date between two Play release (as the Play documentation is for now the only place where Anorm one can be found along).

I'm thinking to have this documentation published through the `gh-pages` of this repository, e.g. [Anorm documentation as GitHub pages](http://cchantep.github.io/anorm/).

- [x] CONTRIBUTING.md
- [x] Highlights: Highlights24.md, Highlights25.md, Highlights26.md, Migration24.md, Migration25.md, Migration26.md
- [x] Try [Cayman](https://pages-themes.github.io/cayman/)

**Comment by cchantep** [comment]
Hi, any news there?

**Comment by cchantep** [comment]
@jroper have you had time to look at this?

**Comment by cchantep** [comment]
Rebased

**Comment by cchantep** [comment]
Can anyone have a look?

**Comment by wsargent** [comment]
So this involves a call to https://github.com/playframework/omnidoc and push?  I'll need to look up the docs.

**Comment by cchantep** [comment]
For now the script is just based on Jekyll, so the doc can be standalone (as no longer following the same release cycle). The auto publication is not done (must be done manually to the `gh-pages`).

**Comment by cchantep** [comment]
Updated at http://cchantep.github.io/anorm/

**Comment by AlexGalays** [comment]
[
![image](https://user-images.githubusercontent.com/1375586/32662364-90ada20e-c62a-11e7-927a-d611f83986af.png)
](url)

**Comment by richdougherty** [comment]
@cchantep - as mentioned on [gitter](https://gitter.im/playframework/contributors?at=5a32e978232e79134d4e553a) you're still waiting on this but I'm not sure what action you need to get this going. Do you want me to enable a setting somewhere? If you let me know then I can help.

**Comment by cchantep** [comment]
Hi @richdougherty , I personally have no access to the settings, and don't want to act on myself w/o prior discussion by publishing that as GitHub pages at `https://playframework.github.io`. Best regards.

**Comment by richdougherty** [comment]
@cchantep I think it's OK to publish something under https://playframework.github.io/anorm. If you push the `gh-pages` branch from your fork then I'll enable publishing on this repo. I'll check with @gmethvin and @marcospereira later this week in case there's a better way to do things, but it seems like a good idea to me so I can enable it for now anyway. Thanks for your patience.

**Comment by richdougherty** [comment]
> I personally have no access to the settings

Hi @cchantep, on second thought I decided the easiest way to resolve this is to give you access to the settings. :) You now have admin access on this repo. If you want to enable Github Pages that's fine with me and @gmethvin.

**Comment by cchantep** [comment]
@richdougherty A first version of the standalone GitHub pages is ready for review at https://cchantep.github.io/anorm/ .

Once ok/merged it will be visible at https://playframework.github.io/anorm/ , or the CNAME can be configured if a DNS is managed.

**Comment by richdougherty** [comment]
> Once ok/merged

It looks OK to me!

> CNAME

Perhaps later we could look at something like https://anorm.playframework.org/? Maybe that's something we can do later because it will take a bit of time to organise.
