### ISSUE TITLE
use a different Calendar for Date/Timestamp/Time get & set

### ISSUE THREAD

**Issue by ChickenSniper** [playframework/anorm#77]
Is there a way to set the Calendar used by Anorm when dealing with Date objects?

I believe that a method such as rs.getTime(x) will use the default java.util.Calendar for the local timezone, but what if I would like to use a Calendar set to UTC?

**Comment by cchantep** [comment]
Hi @ChickenSniper, please use the Play MailingList or [SO tag](http://stackoverflow.com/questions/tagged/anorm) to ask question (rather than this tracker dedicated to confirmed issue). Best regards.
