### ISSUE TITLE
Use table two times in query

### ISSUE THREAD

**Issue by StarWix** [playframework/anorm#78]
Table currency
```
id  | title
-------------------------------
USD | United States dollar
BYR | Belarusian ruble
```
Table rate
```
from | to  
--------------
USD  | BYR
```
I try use one table two times in query:
```SQL
SELECT f.id, f.title, t.id, t.title
FROM rate JOIN currency AS f ON rate.from = f.id
          JOIN currency AS t ON rate.to = t.id
```
and try parse it use this parser:
```scala
val parser: RowParser[Rate] = {
  get[String]("f.id")~
  get[String]("f.title")~
  get[String]("t.id")~
  get[String]("t.title") map {
  case f_id~f_title~t_id~t_title =>
	Rate(Currency(f_id, f_title), Currency(t_id, t_title))
  }
}
```
I receive exception:
```
anorm.AnormException: 'f.id' not found, available columns: currency.id, id, currency.title, title, currency.id, id, currency.title, title
```

If I try use qualified column names as:
```SQL
SELECT f.id AS f_id, f.title AS f_title, t.id AS t_id, t.title AS t_title
FROM rate JOIN currency AS f ON rate.from = f.id
          JOIN currency AS t ON rate.to = t.id
```
and try parse it use this parser:
```scala
val parser: RowParser[Rate] = {
  get[String]("f_id")~
  get[String]("f_title")~
  get[String]("t_id")~
  get[String]("t_title") map {
  case f_id~f_title~t_id~t_title =>
	Rate(Currency(f_id, f_title), Currency(t_id, t_title))
  }
}
```
Result is
```
Rate(Currency(BYR,Belarusian ruble),Currency(BYR,Belarusian ruble))
```
i.e used last columns t_id and t_title.
if I'm swaping columns in query then result is
```
Rate(Currency(USD,United States dollar),Currency(USD,United States dollar))
```

I use anorm 2.5.0

**Comment by cchantep** [comment]
Hi, this tracker is dedicated to confirmed issue in Anorm. Please use [StackOverflow](http://stackoverflow.com/questions/tagged/anorm) to ask question. Best regards.

**Comment by StarWix** [comment]
I think it is bug.
This question is discussed [here](http://stackoverflow.com/questions/32062304/mysql-aliased-tables-in-anorm-are-not-recognized).

**Comment by cchantep** [comment]
As indicated in the [contributor guideline](https://github.com/playframework/anorm/blob/master/CONTRIBUTING.md#anorm-contributor-guidelines), discussion must come first. Best regards.

**Comment by micseydel** [comment]
@StarWix did you ever find a solution? I'm running into this now, and it looks like a bug to me too. I'm getting something akin to
> ID1 not found, available columns : table.id, ID1, table.id, ID2, table.id, ID3
