### ISSUE TITLE
Validate RowParser from query by metadata without executing it

### ISSUE THREAD

**Issue by vdichev** [playframework/anorm#93]
It should be possible to emulate [doobie's query checking](https://tpolecat.github.io/doobie-0.2.3/06-Checking.html) since all the necessary types are already encoded in the parser. This is an example of how I imagine this would look:

```scala
val rowParser = str("name") ~ int("population")
val query = SQL("SELECT * FROM Country")

query.validate(rowParser)
```

It might return an Either or similar showing the validation errors.

Using this feature it should be much easier to check simple type mapping errors and whether the schema matches the types expected in the code. Since no code is executed, it should be safe to perform even on a production database.

**Comment by vdichev** [comment]
OK, I have something working. Of course, validate doesn't always work where applying the parser would work:

* Column[UUID] which depends on the specific value
* RowParser.flatMap doesn't strictly have all the info from the generated parser in the invoked function, but if it's not used directly but through other methods like ~ it should work fine.

**Comment by cchantep** [comment]
I really wonder whether that's the way to go Anorm, considering for me it should stay lightweight, and let the developer responsible.

**Comment by vdichev** [comment]
Well, I can argue that the surface area for the developer is not increased too much with a validate on Sql and Row. You can have a look at the current WIP here: https://github.com/vdichev/anorm/commit/2711f477ab22bc968e41c02b1395c4041e7bc749 (I can submit a pull request when I add some tests). To be honest, most of the functionality is already implemented in some form by the Column.apply methods (although I haven't found a good way to abstract it away yet).

I know there have been similar attempts for validation before (albeit compile-time) in anorm-typed and can say that this is in the same vein but a bit more flexible and just using the information that's already available in the parsers.

**Comment by cchantep** [comment]
For me validating with a connection which can be different from the one used when really executing has very little value.

I don't think Anorm core should try to provide such functions.

You can try to design an optional module.

**Comment by vdichev** [comment]
OK, I'll try that, I understand your reasoning.

**Comment by cchantep** [comment]
(Closing for now)
