### ISSUE TITLE
Release Anorm 2.5.1

### ISSUE THREAD

**Issue by cchantep** [playframework/anorm#95]

**Comment by gmethvin** [comment]
@cchantep I can do the release, but which branch should I release from? Master is `3.0.0-SNAPSHOT`.

**Comment by cchantep** [comment]
From master. Indeed master has been updated to 3.0.0, but it should have been 2.6.0-SNAPSHOT . Master is current in a stable state between 2.5.0 (Aug 2015) and the future 2.6.0.

> As Anorm is no longer supposed to follow the release cycle of Play itself, it would be nice to improve its own release procedure.

**Comment by cchantep** [comment]
(#75 is related to release improvement suggestion)

**Comment by gmethvin** [comment]
Okay. I've done the release of 2.5.1. I would suggest you create a separate 2.5.x branch so you can develop new features separately from the stable branch.

**Comment by cchantep** [comment]
Thanks @gmethvin
